apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifactory

images:
  - name: apigateway-nginx-image
    newName: apigateway-nginx
    newTag: latest

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: apigateway-nginx