
apiVersion: v1
kind: Service
metadata:
  name: apigateway-internal-api
  namespace: artifactory
spec:
  selector:
    app: apigateway
  ports:
    - name: internal-api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP